### PR TITLE
feat: Try to inject parameter value if default value is None

### PR DESCRIPTION
**Pull request by Czaki**
Currently, in-n-out do not allow injecting parameters for function with default value. This does not allow creating an action that has optional injection but will not crash on injection failure. 

A workaround for this may be modifying the signature of the implementation to remove the default value information from the signature. But it is really hacky. 

Alternative to this, PR may define a special generic type to inform that injection should be performed even if a default value is provided.

### CODE REVIEW

**Comment by Czaki** [comment]
it looks like codecov@v3 is broken. Maybe we should add combine steep for codecov?

**Comment by tlambert03** [comment]
thanks @Czaki, I added a test.  
The issue with codecov is annoying. I want to use codecov v4, but I also want to keep using reusable workflows, and I'm struggling to pass the token to the reusable workflow when the action is triggered by a PR from a fork.  How are you dealing with that?  I see a similar setup in your workflows in napari, where you're just passing:

```yaml
    uses: ./.github/workflows/reusable_coverage_upload.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
 ```

but for some reason it's working there but not here.  (note that I currently use `secrets: inherit`, but I don't think it matters... I also tried the explicit passing of `codecov-token`).  Anyway, I'll figure that out in a later PR.  Thanks for this good fix

**Comment by Czaki** [comment]
We do not do this. Codecov fixed their action and version 4 allow tokenless upload from a fork of  public repository.

However time to time we hit api response problems. Because of this we upload coverage in separate steep.

**Comment by Czaki** [comment]
> oh! well that's exciting. somehow I missed this important detail 😂 that's great.

It was fixed a few months after v4 release

**Comment by tlambert03** [comment]
thanks.  yeah, it's all working fine now. I just removed the codecov v3 fallback logic from the reusable workflow and it just does the right thing for PRs from forks

**Pull request merged**
